//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexicalAnalysisTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LexicalAnalysisTests.Properties.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program_kezd
        ///egész x = 2
        ///program_kezd
        ///x = x + 1
        ///program_vége.
        /// </summary>
        internal static string MultipleStart {
            get {
                return ResourceManager.GetString("MultipleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program_kezd
        ///x = x + 1
        ///program_vége.
        /// </summary>
        internal static string NoType {
            get {
                return ResourceManager.GetString("NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program_kezd
        ///egész a
        ///egész b
        ///logikai a
        ///egész[] tömb = létrehoz(egész)[10]
        ///szöveg error
        ///logikai lenniVAGYnemLENNI
        ///tört burgonya = 2,3
        ///program_vége.
        /// </summary>
        internal static string Redeclaration {
            get {
                return ResourceManager.GetString("Redeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program_kezd
        ///egész x = 2;
        ///egész y = 3;
        ///y = x + y;
        ///x = x + 1;
        ///program_vége.
        /// </summary>
        internal static string UnknownSymbol {
            get {
                return ResourceManager.GetString("UnknownSymbol", resourceCulture);
            }
        }
    }
}
